### ISSUE TITLE
Fase 1 - Parametros (Decoding)

### ISSUE THREAD

**Issue by tmldsousa** [isel-leic-ls/1516-2-common#2]
@pmhsfelix @fbfreitas 
Nos requisitos da fase 1, na secção "Management Application", os professores referem:

> - the `parameters` is a sequence of `name=value` pairs, separated by `&` (e.g. `name=LS&description=software+laboratory`).
- Para além de interpretar os conjuntos "chave=valor" presentes na string, também temos de fazer o _decoding_ do valor (No exemplo: software+library => "software library")?
- Se sim, para efectuar este decode, podemos usar classes do java (como [java.net.URLDecoder](http://docs.oracle.com/javase/7/docs/api/java/net/URLDecoder.html#URLDecoder%28%29))?
- Caso tenhamos de fazer a nossa lógica de decode, que caracteres especiais temos de ter em consideração?

@isel-leic-ls/1516-2-li41n-g12-team

**Comment by pmhsfelix** [comment]
- Sim, tem de fazer o URL decode.
- Sim, podem usar funcionalidades presentes na biblioteca de classes do Java
