### ISSUE TITLE
post review

### ISSUE THREAD

**Issue by mvcorrea** [isel-leic-ls/1516-2-common#3]
Boas, 

Uma pergunta, no caso abaixo.

POST
/movies/2/reviews
reviewerName=mvcorrea&reviewSummary=myreviewSumm2&review=myreview2&**rating=2**

o que sera o rating? um "rating id" (previamente criado na tabela de ratings) ou um "rating value" (onde irei ter de criar o rating antes de criar o review)

obr,
Marcelo

**Comment by pmhsfelix** [comment]
É o valor do _rating_.
